#!/bin/sh
# /usr/lib/frpc/generate_toml.sh
# Generate /etc/frp/frpc.toml from UCI /etc/config/frpc
# POSIX sh compatible (no bashisms)
set -e

FRPC_CONFIG="/etc/config/frpc"
OUTPUT_FILE="/etc/frp/frpc.toml"

# ---- helpers ----

# Read a UCI option from the main section.
#   uci_get <option> [default]
uci_get() {
    local val
    val=$(uci -q get "$FRPC_CONFIG.main.$1" 2>/dev/null) || true
    [ -n "$val" ] && { echo "$val"; return; }
    [ -n "${2+x}" ] && echo "$2"
}

# Read a UCI option from the given section variable.
#   sec_get <section_id> <option> [default]
sec_get() {
    local val
    val=$(uci -q get "$FRPC_CONFIG.$1.$2" 2>/dev/null) || true
    [ -n "$val" ] && { echo "$val"; return; }
    [ -n "${3+x}" ] && echo "$3"
}

# Print a TOML key = "value" line (quoted).
emit() {
    printf '%s = "%s"\n' "$1" "$2"
}

# Print a TOML key = value line (unquoted).
emit_raw() {
    printf '%s = %s\n' "$1" "$2"
}

# Print a TOML key = integer line.
emit_int() {
    printf '%s = %d\n' "$1" "$2"
}

# Parse pipe-separated "Key:Value|Key2:Value2" into TOML inline table.
#   emit_map <section_prefix>  e.g. "[proxy.requestHeaders]"
# Each entry: Key:Value  (colon separates key from value)
emit_map() {
    local section_name="$1"
    local raw="$2"
    [ -z "$raw" ] && return 1

    printf '%s\n' "$section_name"
    echo "$raw" | tr '|' '\n' | while IFS= read -r entry; do
        entry=$(echo "$entry" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [ -z "$entry" ] && continue
        local key="${entry%%:*}"
        local val="${entry#*:}"
        key=$(echo "$key" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        val=$(echo "$val" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [ -n "$key" ] && printf '%s = "%s"\n' "$key" "$val"
    done
    return 0
}

# Parse pipe-separated list into TOML array: ["item1", "item2"]
#   emit_array <key> <pipe_separated_string>
emit_array() {
    local key="$1"
    local raw="$2"
    [ -z "$raw" ] && return 1

    local result="["
    local first=true
    echo "$raw" | tr '|' '\n' | while IFS= read -r item; do
        item=$(echo "$item" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [ -z "$item" ] && continue
        if [ "$first" = true ]; then
            printf '%s = ["%s"' "$key" "$item"
            first=false
        else
            printf ', "%s"' "$item"
        fi
    done
    printf ']\n'
    return 0
}

# ---- client common ----

generate_client() {
    local server_addr tls_enable token server_port
    local auth_type auth_token
    local transport_protocol tcp_mux pool_count
    local heartbeat_interval heartbeat_timeout
    local log_level log_max_days
    local dns_server login_fail_exit metadatas

    server_addr=$(uci_get server_addr "")
    tls_enable=$(uci_get tls "0")
    token=$(uci_get auth_token "")
    server_port=$(uci_get server_port 7000)
    auth_type=$(uci_get auth_type "token")

    # Transport
    transport_protocol=$(uci_get transport_protocol "")
    tcp_mux=$(uci_get tcp_mux "0")
    pool_count=$(uci_get pool_count "")
    heartbeat_interval=$(uci_get heartbeat_interval "")
    heartbeat_timeout=$(uci_get heartbeat_timeout "")

    # Log
    log_level=$(uci_get log_level "")
    log_max_days=$(uci_get log_max_days "")

    # Advanced
    dns_server=$(uci_get dns_server "")
    login_fail_exit=$(uci_get login_fail_exit "1")
    metadatas=$(uci_get metadatas "")

    # Validate required fields
    if [ -z "$server_addr" ]; then
        echo "Error: server_addr is required" >&2
        exit 1
    fi
    if [ -z "$token" ]; then
        echo "Error: auth token is required" >&2
        exit 1
    fi

    # ---- output ----
    cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by luci-app-frpc-new — do not edit manually
# $(date '+%Y-%m-%d %H:%M:%S')

serverAddr = "$server_addr"
serverPort = $server_port
loginFailExit = $([ "$login_fail_exit" = "0" ] && echo false || echo true)

EOF

    # DNS server
    [ -n "$dns_server" ] && echo "dnsServer = \"$dns_server\"" >> "$OUTPUT_FILE"

    # Auth section
    cat >> "$OUTPUT_FILE" <<EOF

[auth]
method = "$auth_type"
token = "$token"

EOF

    # Transport section
    cat >> "$OUTPUT_FILE" <<EOF
[transport]
poolCount = ${pool_count:-1}
EOF

    # Protocol (tcp/kcp/quic/wss)
    if [ -n "$transport_protocol" ]; then
        echo "protocol = \"$transport_protocol\"" >> "$OUTPUT_FILE"
    fi

    # TCP mux
    [ "$tcp_mux" = "1" ] && echo "tcpMux = true" >> "$OUTPUT_FILE"

    # Heartbeat
    [ -n "$heartbeat_interval" ] && echo "heartbeatInterval = $heartbeat_interval" >> "$OUTPUT_FILE"
    [ -n "$heartbeat_timeout" ] && echo "heartbeatTimeout = $heartbeat_timeout" >> "$OUTPUT_FILE"

    # TLS
    if [ "$tls_enable" = "1" ]; then
        cat >> "$OUTPUT_FILE" <<EOF

[transport.tls]
enable = true
EOF
    fi

    # Log section
    if [ -n "$log_level" ] || [ -n "$log_max_days" ]; then
        echo "" >> "$OUTPUT_FILE"
        echo "[log]" >> "$OUTPUT_FILE"
        [ -n "$log_level" ] && echo "level = \"$log_level\"" >> "$OUTPUT_FILE"
        [ -n "$log_max_days" ] && echo "maxDays = $log_max_days" >> "$OUTPUT_FILE"
    fi

    # Client metadatas
    if [ -n "$metadatas" ]; then
        emit_map "[metadatas]" "$metadatas" >> "$OUTPUT_FILE"
    fi
}

# ---- proxy ----

generate_proxy() {
    local section="$1"
    local name type local_ip local_port
    local remote_port custom_domains subdomain
    local http_user http_pwd
    local host_header_rewrite locations
    local request_headers response_headers
    local route_by_http_user multiplexer
    local use_encryption use_compression
    local bandwidth_limit bandwidth_limit_mode
    local transport_type proxy_protocol_version pool_count
    local health_check_type health_check_timeout_s
    local health_check_max_failed health_check_interval_s
    local health_check_path health_check_headers
    local plugin_type plugin_user plugin_pass
    local plugin_local_path plugin_strip_prefix
    local plugin_http_user plugin_http_passwd
    local plugin_addr sni_rewrite
    local secret_key role server_name allow_users
    local metadatas

    name=$(sec_get "$section" name "")
    type=$(sec_get "$section" type "tcp")
    local_ip=$(sec_get "$section" local_ip "127.0.0.1")
    local_port=$(sec_get "$section" local_port "")

    if [ -z "$name" ] || [ -z "$local_port" ]; then
        echo "Warning: proxy $section missing name or local_port, skipping" >&2
        return
    fi

    echo "[[proxies]]" >> "$OUTPUT_FILE"
    emit "name" "$name"
    emit "type" "$type"
    emit "localIP" "$local_ip"
    emit_int "localPort" "$local_port"

    # TCP/UDP/SUDP: remotePort
    if [ "$type" = "tcp" ] || [ "$type" = "udp" ] || [ "$type" = "sudp" ]; then
        remote_port=$(sec_get "$section" remote_port "")
        [ -n "$remote_port" ] && emit_int "remotePort" "$remote_port"
    fi

    # HTTP/HTTPS/TCPMux: domains, subdomain, HTTP settings
    if [ "$type" = "http" ] || [ "$type" = "https" ] || [ "$type" = "tcpmux" ]; then
        custom_domains=$(sec_get "$section" custom_domains "")
        subdomain=$(sec_get "$section" subdomain "")

        if [ -n "$custom_domains" ]; then
            # Build TOML array: customDomains = ["d1", "d2"]
            printf 'customDomains = ['
            local first=true
            echo "$custom_domains" | tr ',' '\n' | while IFS= read -r d; do
                d=$(echo "$d" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                [ -z "$d" ] && continue
                if [ "$first" = true ]; then
                    printf '"%s"' "$d"
                    first=false
                else
                    printf ', "%s"' "$d"
                fi
            done
            printf ']\n'
        fi

        [ -n "$subdomain" ] && emit "subdomain" "$subdomain"
    fi

    # HTTP/HTTPS: httpUser, httpPassword, hostHeaderRewrite, locations, headers, routeByHTTPUser
    if [ "$type" = "http" ] || [ "$type" = "https" ]; then
        http_user=$(sec_get "$section" http_user "")
        http_pwd=$(sec_get "$section" http_pwd "")
        [ -n "$http_user" ] && emit "httpUser" "$http_user"
        [ -n "$http_pwd" ] && emit "httpPassword" "$http_pwd"

        route_by_http_user=$(sec_get "$section" route_by_http_user "")
        [ -n "$route_by_http_user" ] && emit "routeByHTTPUser" "$route_by_http_user"

        response_headers=$(sec_get "$section" response_headers "")
        [ -n "$response_headers" ] && emit_map "[proxies.responseHeaders]" "$response_headers"
    fi

    # HTTP/HTTPS/TCPMux: hostHeaderRewrite, locations, multiplexer, requestHeaders
    if [ "$type" = "http" ] || [ "$type" = "https" ] || [ "$type" = "tcpmux" ]; then
        host_header_rewrite=$(sec_get "$section" host_header_rewrite "")
        [ -n "$host_header_rewrite" ] && emit "hostHeaderRewrite" "$host_header_rewrite"

        multiplexer=$(sec_get "$section" multiplexer "")
        [ -n "$multiplexer" ] && emit "multiplexer" "$multiplexer"

        locations=$(sec_get "$section" locations "")
        if [ -n "$locations" ]; then
            printf 'locations = ['
            local first=true
            echo "$locations" | tr '|' '\n' | while IFS= read -r loc; do
                loc=$(echo "$loc" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                [ -z "$loc" ] && continue
                if [ "$first" = true ]; then
                    printf '"%s"' "$loc"
                    first=false
                else
                    printf ', "%s"' "$loc"
                fi
            done
            printf ']\n'
        fi

        request_headers=$(sec_get "$section" request_headers "")
        [ -n "$request_headers" ] && emit_map "[proxies.requestHeaders]" "$request_headers"
    fi

    # Plugin
    plugin_type=$(sec_get "$section" plugin_type "")
    if [ -n "$plugin_type" ]; then
        printf '[proxies.plugin]\n'
        case "$plugin_type" in
            socks5)
                plugin_user=$(sec_get "$section" plugin_user "")
                plugin_pass=$(sec_get "$section" plugin_pass "")
                emit "type" "socks5"
                [ -n "$plugin_user" ] && emit "user" "$plugin_user"
                [ -n "$plugin_pass" ] && { emit "passwd" "$plugin_pass"; }
                ;;
            http_proxy)
                plugin_user=$(sec_get "$section" plugin_user "")
                plugin_pass=$(sec_get "$section" plugin_pass "")
                emit "type" "http_proxy"
                [ -n "$plugin_user" ] && { emit "httpUser" "$plugin_user"; }
                [ -n "$plugin_pass" ] && { emit "httpPassword" "$plugin_pass"; }
                ;;
            static_file)
                plugin_local_path=$(sec_get "$section" plugin_local_path "")
                plugin_strip_prefix=$(sec_get "$section" plugin_strip_prefix "")
                plugin_http_user=$(sec_get "$section" plugin_http_user "")
                plugin_http_passwd=$(sec_get "$section" plugin_http_passwd "")
                emit "type" "static_file"
                [ -n "$plugin_local_path" ] && emit "localPath" "$plugin_local_path"
                [ -n "$plugin_strip_prefix" ] && emit "stripPrefix" "$plugin_strip_prefix"
                [ -n "$plugin_http_user" ] && { emit "httpUser" "$plugin_http_user"; }
                [ -n "$plugin_http_passwd" ] && { emit "httpPassword" "$plugin_http_passwd"; }
                ;;
            unix_domain_socket)
                plugin_addr=$(sec_get "$section" plugin_addr "")
                emit "type" "unix_domain_socket"
                [ -n "$plugin_addr" ] && emit "addr" "$plugin_addr"
                ;;
            http2socks)
                plugin_local_path=$(sec_get "$section" plugin_local_path "")
                emit "type" "http2socks"
                [ -n "$plugin_local_path" ] && emit "localPath" "$plugin_local_path"
                ;;
            sni)
                sni_rewrite=$(sec_get "$section" sni_rewrite "")
                emit "type" "sni"
                [ -n "$sni_rewrite" ] && emit "hostHeaderRewrite" "$sni_rewrite"
                ;;
        esac
        echo ""
    fi

    # Proxy transport settings
    use_encryption=$(sec_get "$section" use_encryption "")
    use_compression=$(sec_get "$section" use_compression "")
    bandwidth_limit=$(sec_get "$section" bandwidth_limit "")
    bandwidth_limit_mode=$(sec_get "$section" bandwidth_limit_mode "")
    transport_type=$(sec_get "$section" transport_type "")
    proxy_protocol_version=$(sec_get "$section" proxy_protocol_version "")
    pool_count=$(sec_get "$section" pool_count "")

    if [ -n "$use_encryption" ] || [ -n "$use_compression" ] || [ -n "$bandwidth_limit" ] || \
       [ -n "$transport_type" ] || [ -n "$proxy_protocol_version" ] || [ -n "$pool_count" ]; then
        printf '[proxies.transport]\n'
        [ -n "$use_encryption" ] && emit_raw "useEncryption" "$use_encryption"
        [ -n "$use_compression" ] && emit_raw "useCompression" "$use_compression"
        [ -n "$bandwidth_limit" ] && emit "bandwidthLimit" "$bandwidth_limit"
        [ -n "$bandwidth_limit_mode" ] && emit "bandwidthLimitMode" "$bandwidth_limit_mode"
        [ -n "$transport_type" ] && emit "transportType" "$transport_type"
        [ -n "$proxy_protocol_version" ] && emit "proxyProtocolVersion" "$proxy_protocol_version"
        [ -n "$pool_count" ] && emit_int "poolCount" "$pool_count"
        echo ""
    fi

    # STCP/XTCP/SUDP: secretKey, role, serverName, allowUsers
    if [ "$type" = "stcp" ] || [ "$type" = "xtcp" ] || [ "$type" = "sudp" ]; then
        secret_key=$(sec_get "$section" secret_key "")
        role=$(sec_get "$section" role "")
        server_name=$(sec_get "$section" server_name "")
        allow_users=$(sec_get "$section" allow_users "")

        [ -n "$secret_key" ] && emit "secretKey" "$secret_key"
        [ -n "$role" ] && emit "role" "$role"
        [ -n "$server_name" ] && emit "serverName" "$server_name"

        if [ -n "$allow_users" ]; then
            printf 'allowUsers = ['
            local first=true
            echo "$allow_users" | tr ',' '\n' | while IFS= read -r u; do
                u=$(echo "$u" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
                [ -z "$u" ] && continue
                if [ "$first" = true ]; then
                    printf '"%s"' "$u"
                    first=false
                else
                    printf ', "%s"' "$u"
                fi
            done
            printf ']\n'
        fi
    fi

    # Health check
    health_check_type=$(sec_get "$section" health_check_type "")
    if [ -n "$health_check_type" ]; then
        printf '[proxies.healthCheck]\n'
        emit "type" "$health_check_type"
        health_check_timeout_s=$(sec_get "$section" health_check_timeout_s "")
        health_check_max_failed=$(sec_get "$section" health_check_max_failed "")
        health_check_interval_s=$(sec_get "$section" health_check_interval_s "")
        [ -n "$health_check_timeout_s" ] && emit_int "timeoutSeconds" "$health_check_timeout_s"
        [ -n "$health_check_max_failed" ] && emit_int "maxFailed" "$health_check_max_failed"
        [ -n "$health_check_interval_s" ] && emit_int "intervalSeconds" "$health_check_interval_s"

        if [ "$health_check_type" = "http" ]; then
            health_check_path=$(sec_get "$section" health_check_path "")
            health_check_headers=$(sec_get "$section" health_check_headers "")
            [ -n "$health_check_path" ] && emit "path" "$health_check_path"
            [ -n "$health_check_headers" ] && emit_map "[proxies.healthCheck.httpHeaders]" "$health_check_headers"
        fi
        echo ""
    fi

    # Proxy metadatas
    metadatas=$(sec_get "$section" metadatas "")
    [ -n "$metadatas" ] && emit_map "[proxies.metadatas]" "$metadatas"

    echo "" >> "$OUTPUT_FILE"
}

# ---- main ----

mkdir -p "$(dirname "$OUTPUT_FILE")"
generate_client

# Append each enabled proxy
for section in $(uci -q show "$FRPC_CONFIG" | grep "\.enabled='1'" | cut -d. -f2 | sort -u); do
    generate_proxy "$section" >> "$OUTPUT_FILE"
done

# Verify generated config
if command -v frpc >/dev/null 2>&1; then
    if ! frpc verify -c "$OUTPUT_FILE" >/dev/null 2>&1; then
        echo "Warning: generated frpc.toml has syntax errors, check config" >&2
    fi
fi

echo "Generated $OUTPUT_FILE at $(date)"
